### ISSUE TITLE
Cannot load init file in Linux

### ISSUE THREAD

**Issue by andrew-wilkes** [Thane5/godot-clipboard-panel#1]
Linux is case sensitive and Godot tries to load Clipboard_init.gd and fails, so please rename this file and in the .cfg file.

**Comment by Thane5** [comment]
Should be fixed with 66b85e7

**Comment by Hakunamawatta** [comment]
If you made a change to the cfg file, it seems you forgot to add it in your commit.
